<a href="https://colab.research.google.com/github/juwimana/Python-Beginner-Practice-Exercises-/blob/main/basic_operations_with_matrices__exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TASK:** import numpy

In [1]:
import numpy as np

**TASK:** define vector 'x' with three coordinates

In [21]:
x = np.array([2,3,6])

**TASK:** define (2 x 2) matrix 'A' 


In [102]:
A = np.array([[2,3],[5,1]])

**TASK:** define (2 x 2) matrix 'B'

In [4]:
B = np.array([[8,3],[1,2]])

**TASK:** check the type of 'x'

In [22]:
type(x)

numpy.ndarray

**TASK:** check the type of 'A'

In [16]:
type(A)

numpy.ndarray

**TASK:**  check the shape of 'x'


In [23]:
x.shape

(3,)

**TASK:** check the type of 'B'

In [25]:
type(B)

numpy.ndarray

**TASK:** 

In [ ]:
"""
Define function 'have_same_shape' which checks if two arrays have same shape.

PARAMS:
    array_1 (numpy.ndarray) - first array
    array_2 (numpy.ndarray) - second array
RETURN:
    True - if arrays have same shape
    False - if arrays do not have same shape

Also print 'Arrays must have same shape!' when returning False
"""

In [29]:
def have_same_shape(A,B):
  if A.shape == B.shape:
    return True
  else:
    print("Arrays must have the same shape\n")
    return False


**TASK:** call the function 'have_same_shape' with matrix 'A' and vector 'x' as inputs

In [30]:
have_same_shape(A,x)

Arrays must have the same shape



False

**TASK:**  call the function 'have_same_shape' with matrix 'A' and matrix 'B' as inputs

In [31]:
have_same_shape(A,B)

True

**TASK:** 

In [ ]:
"""
Define function 'matrix_addition' which perform matrix addition value by value.

PARAMS:
    A (numpy.ndarray) - first array
    B (numpy.ndarray) - second array
RETURN:
    C (numpy.ndarray) - new A+B array

In this task do not consider broadcasting.
Do not forget to check arrays shapes (you can use 'have_same_shape' function defined before)

"""


In [42]:
def matrix_addition(A,B):
  #check shape
  if have_same_shape(A,B) == True:
    C = A + B
    return C
  else:
    print("Can't add arrays due to different shape")

**TASK:** call the function 'matrix_addition' with matrix 'A' and matrix 'B' as inputs

In [40]:
matrix_addition(A,B)

array([[10,  6],
       [ 6,  3]])

In [43]:
matrix_addition(A,x)

Arrays must have the same shape

Can't add arrays due to different shape


**TASK:** 

In [ ]:
"""
Define 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition

PARAMS:
   lst_of_arr (list) - list of numpy.ndarrays
RETURN:
    NEW_ARRAY (numpy.ndarray) - new array

Use 'matrix_addition' function defined before.
"""

"\nDefine 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition\n\nPARAMS:\n   lst_of_arr (list) - list of numpy.ndarrays\nRETURN:\n    NEW_ARRAY (numpy.ndarray) - new array\n\nUse 'matrix_addition' function defined before.\n"

In [109]:
def multiple_matrix_addition(list):
  i = 0
  M = list[i]
  print(M)

  while i < len(list):
    M = matrix_addition(list[i],M)
    print(M)
    i = i + 1

  return M


**TASK:** call the function 'multiple_matrix_addition' with matrix [A,A,B,B,B] as input


In [110]:
multiple_matrix_addition([A,B,B,B])

[[2 3]
 [5 1]]
[[ 4  6]
 [10  2]]
[[12  9]
 [11  4]]
[[20 12]
 [12  6]]
[[28 15]
 [13  8]]


array([[28, 15],
       [13,  8]])

**TASK:** 

In [ ]:
"""
Define function 'can_multiply' that checks if two arrays (matrices) can be multiplied

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    True - if arrays can be multiplied, also print the shape of the new array
    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'
    
"""

In [114]:
def can_multiply(A,B):
  if A.shape[1] == B.shape[0]:
    print("({},{})".format(A.shape[0],A.shape[1]))
    return True
  else: 
    print("Matrices can not be multipled")
    return False

**TASK:** call the function 'can_multiply' with matrix 'A' and 'B' as inputs

In [115]:
can_multiply(A,B)

(2,2)


True

**TASK:**  define matrix (3 x 2) matrix C

In [121]:
C = np.array([[1,2],[7,5],[3,10]])
C

array([[ 1,  2],
       [ 7,  5],
       [ 3, 10]])

**TASK:**  call the function 'can_multiply' with matrix 'A' and 'C' as inputs

In [117]:
can_multiply(A,C)

Matrices can not be multipled


False

**TASK:**  call the function 'can_multiply' with matrix 'C' and 'A' as inputs (now C,A not A,C). Do you know why is the result different?

In [118]:
can_multiply(C,A)

(3,2)


True

**TASK:** 

In [ ]:
"""
Define function 'matrix_multiplication' that multiply two numpy.ndarrays

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    NEW_ARRAY (numpy.ndarray) - new A * B array
    
Do not forget to check if two matrices can be multiplied.

"""

In [119]:
def matrix_multiplication(A,B):
  if can_multiply(A,B) == True:
    C = A.dot(B)
    return C
  else:
    return False

**TASK:**  call the function 'matrix_multiplication' with matrix 'C' and 'B' 


In [120]:
matrix_multiplication(C,B)

(3,2)


array([[10,  7],
       [61, 31],
       [34, 29]])

In [125]:
matrix_multiplication(B,C)

Matrices can not be multipled


False

**TASK:** call the function 'matrix_multiplication' with matrix 'A' and 'C' 

In [122]:
matrix_multiplication(A,C)

Matrices can not be multipled


False

In [126]:
matrix_multiplication(C,A)

(3,2)


array([[12,  5],
       [39, 26],
       [56, 19]])