<a href="https://colab.research.google.com/github/juwimana/Python-Beginner-Practice-Exercises-/blob/main/Numpy_Working_With_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Create a Matrix
* import numpy 
* create matrix A
* check the type of A using type() method
* use shape to check the dimensions of matrix A (A.shape)
* find the lenght of matrix A (len(A))

In [1]:
#import numpy
import numpy as np

In [17]:
#creating a 3*2 matrix (a 2-dimensional array)
A = np.array([[1,2],[3,4],[5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
#checking type of A
type(A)

numpy.ndarray

In [4]:
#The shape of an array tells us the number of values for each dimension
A.shape
#We can see from the result that A has 3 rows and 2 columns

(3, 2)

In [6]:
#The length of the array 
len(A)

3

# Matrix Transpose
* use transpose() method OR A.T to find the transpose of matrix A
* use shape to find the dimensions of the transposed matrix

In [12]:
#we can transpose a matrix by using the transpose() method of numpy.ndarray object
A_transpose = A.transpose()
print(A_T)

#OR you can use A.T to get same result
print("\n {}".format(A.T))

[[1 3 5]
 [2 4 6]]

 [[1 3 5]
 [2 4 6]]


In [13]:
#shape should give the new dimensions of A transposed
A_T.shape

(2, 3)

# Matrix Addition
* Numpy can handle operations on arrays of different shapes. 
* A smaller array will be extended to match the shape of a bigger one. This is called broadcasting
* For example, when adding a scalar to a matrix, the scalar is converted to an array of the same dimension of the Matrix (check code below for **D = C + 5**)

In [14]:
#define new matrix B 
B =  np.array([[2, 5], [7, 4], [4, 3]])
B

array([[2, 5],
       [7, 4],
       [4, 3]])

In [22]:
#find shape of B
B.shape

(3, 2)

In [16]:
#Add B to A to get C = A + B
C = A + B
C

array([[ 3,  7],
       [10,  8],
       [ 9,  9]])

In [18]:
#you can a scalar value to a matrix
#add 4 to C to get D = C + 5 (each cell of C is increased by 5)
D = C + 5
D

array([[ 8, 12],
       [15, 13],
       [14, 14]])

# Matrix Multiplication
* A matrix product is also called a dot product
* use dot() function in numpy to find the dot product of matrix A and matrix D save as matrix M 
* AB != BA
* Matrix multiplication is only possible when the dimensions of the two matrices have the same number of rows and columns i.e. A has dimensions (m,n) and D has dimensions (n,k)
* The result will be matrix M with dimensions (m,k)

In [23]:
#create matrix D
D = B.T
D

array([[2, 7, 4],
       [5, 4, 3]])

In [24]:
#check shape of D
D.shape

(2, 3)

In [26]:
#using np.dot(A,D)
M = np.dot(A,D)
print(M)

#using A.dot(D)
M = A.dot(D)
print("\n {}".format(M))

[[12 15 10]
 [26 37 24]
 [40 59 38]]

 [[12 15 10]
 [26 37 24]
 [40 59 38]]


In [27]:
#check shape of D; should be A(3,2), D(2,3) therefore M(3,3)
M.shape

(3, 3)

# Identity Matrix
* identity matrix (denote **I**)is a diagonal, square matrix with ones on the main diagonal, and zeros on the off diagonal
* numpy function eye() is used to create an identity matrix; eye() takes an argument which represents the dimension of the square matrix. 
* For example, np.eye(3) creates a 3x3 identity matrix
*  the identity matrix is that it is commutative, associative, and
distributive with respect to multiplication
* the product of an identity matrix with another matrix returns the same matrix **(AI = IA = A)**

In [32]:
#create an identity matrix
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
#find shape of I
I.shape

(3, 3)

In [35]:
#sot product of I and M
MI = I.dot(M)
MI

array([[12., 15., 10.],
       [26., 37., 24.],
       [40., 59., 38.]])

# Determinant of a Matrix
* we need the numpy.linalg module to compute the determinant of a matrix
* determinant can only be computed on square matrices (n,n)
* if the determinant of a matrix equals zero, then the matrix is said to be singular, or not invertable (for example matrix M)
* if the determinant of A is non-zero, then A is said to be nonsingular, or invertable (for example matrix P)

In [45]:
print(A.shape,B.shape,C.shape,D.shape,M.shape)

(3, 2) (3, 2) (3, 2) (2, 3) (3, 3)


In [46]:
#compute the determinant of M since its the only square matrix we have (3,3)
det_M = np.linalg.det(M) 
det_M

0.0

In [53]:
#create a new matrix P 
P = np.array([[1,2,3],[5,3,1],[10,4,1]])
print(P)
print("\n {}".format(P.shape))

[[ 1  2  3]
 [ 5  3  1]
 [10  4  1]]

 (3, 3)


In [68]:
#find determinant of P since its a square matrix
det_P = np.linalg.det(P)
det_P

-21.0

# Inverse Matrix
* the inverse of a matrix A is the matrix that results in the identity matrix when multiplied by A 
* use the numpy function linalg.inv() to calculate the inverse of a matrix
* The inverse of a matrix is only possible on square matrices (n,n)

In [66]:
#find the inverse of P 
inv_P = np.linalg.inv(P)
print(np.round(inv_P))
print("\n {}".format(inv_P.shape))

[[ 0. -0.  0.]
 [-0.  1. -1.]
 [ 0. -1.  0.]]

 (3, 3)


In [67]:
#check that our inverse is correct
I = np.round(inv_P.dot(P))
I

array([[ 1.,  0.,  0.],
       [-0.,  1., -0.],
       [ 0.,  0.,  1.]])

In [57]:
#matrix M has no inverse since the determinant is zero. We get an LinAlgErrot that M is singular (not invertible)
inv_M = np.linalg.inv(M)
print(inv_M)

LinAlgError: ignored