### Load Data From File

In [1]:
import numpy as np

In [14]:
data = np.genfromtxt('data.txt',delimiter = ',')
#change type from float to int
data = data.astype('int32')
data

array([[          1,           3,          87,          34,           2,
                 76,           9,          10,          33,         390,
        -2147483648],
       [         84,          18,          28,           4,           6,
                 84,          94,           1,           4,           6,
        -2147483648],
       [        943,           7,           0,           3,           3,
                  6,           3,           8,           9,          54,
        -2147483648],
       [          7,          32,         123,          44,          67,
                 84,          19,           0,           3,          23,
        -2147483648],
       [          1,           2,           4,           6,           7,
                 88,          88,           8,          90,          23,
        -2147483648]])

### Boolean Masking and Advanced Indexing

In [16]:
#return values greater that 50
data[data > 50]

array([ 87,  76, 390,  84,  84,  94, 943,  54, 123,  67,  84,  88,  88,
        90])

In [17]:
#check if we have zero values
data[data==0]

array([0, 0])

In [18]:
#check if we have negative values
data[data<0]

array([-2147483648, -2147483648, -2147483648, -2147483648, -2147483648])

In [19]:
np.any(data>50, axis=0)

array([ True, False,  True, False,  True,  True,  True, False,  True,
        True, False])

In [20]:
np.any(data>50, axis=1)

array([ True,  True,  True,  True,  True])

In [21]:
((data>50)&(data<200))

array([[False, False,  True, False, False,  True, False, False, False,
        False, False],
       [ True, False, False, False, False,  True,  True, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
         True, False],
       [False, False,  True, False,  True,  True, False, False, False,
        False, False],
       [False, False, False, False, False,  True,  True, False,  True,
        False, False]])

In [22]:
sum(data)

array([       1036,          62,         242,          91,          85,
               338,         213,          27,         139,         496,
       -2147483648])

In [25]:
sum(data)

array([       1036,          62,         242,          91,          85,
               338,         213,          27,         139,         496,
       -2147483648])