### Learn NumPy
[Click For More](https://numpy.org/)

#### Import Library

In [1]:
import numpy as np

#### Basics of NumPy

In [3]:
#create a numpy array A
A = np.array([1,2,3])
print(A)

[1 2 3]


In [9]:
#create numpy array B
B = np.array([[2.0,4.0,5.0],[6.0,8.0,10.0]])
print(B)

[[ 2.  4.  5.]
 [ 6.  8. 10.]]


In [12]:
#get dimension of A and B
print(A.ndim)
print(B.ndim)

1
2


In [13]:
#get shape of A and B
print(A.shape)
print(B.shape)

(3,)
(2, 3)


In [14]:
#get type of A and B
print(type(A))
print(type(B))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [15]:
#get size of A and B
print(A.itemsize)
print(B.itemsize)

4
8


In [16]:
#get total size of A and B
print(A.nbytes)
print(B.nbytes)

12
48


#### Modify NumPy Arrays

In [52]:
#create numpy array C
C = np.array([[1,2,3,4,5,6],[8,9,10,11,12,13]])
print(C)

[[ 1  2  3  4  5  6]
 [ 8  9 10 11 12 13]]


In [53]:
#get a specific element from C [r,c]
C[1,3]

11

In [54]:
#get a specific row [r,:]
C[0,:]

array([1, 2, 3, 4, 5, 6])

In [55]:
#get a specific column [:,c]
print(C[:,0])
print(C[:,3])
print(C[:,5])

[1 8]
[ 4 11]
[ 6 13]


In [56]:
#get more info from C [startindex:endindex:stepsize]
print(C[0, 2:-1:2])
print(C[0, 3:-1:1])
print(C[1, 0:-1:2])
print(C[1, 0:-1:5])

[3 5]
[4 5]
[ 8 10 12]
[8]


In [59]:
#change values of rows/column/element
C[1,4] = 100
print(C)

C[:,3] = 200
print(C)

C[1,:] = 25
print(C)

[[  1   2   3 200   5   6]
 [  8   9  10 200 100  13]]
[[  1   2   3 200   5   6]
 [  8   9  10 200 100  13]]
[[  1   2   3 200   5   6]
 [ 25  25  25  25  25  25]]


In [63]:
#create numpy 3D array
D = np.array([[[1,2,3],[4,2,7]],[[1,0,9],[3,7,2]]])
print(D)

[[[1 2 3]
  [4 2 7]]

 [[1 0 9]
  [3 7 2]]]


In [65]:
#access elements of D
D[1,0,1]

0

In [70]:
#replace 
D[:,1,:] = [[4,6,7],[0,1,3]]
D

array([[[1, 2, 3],
        [4, 6, 7]],

       [[1, 0, 9],
        [0, 1, 3]]])

#### Initialize Different Types of Arrays
[Click For More](https://numpy.org/doc/stable/reference/routines.array-creation.html)

In [73]:
#all zeros array or matrix
print(np.zeros(5))
print(np.zeros((3,3)))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [75]:
#all ones array or matrix
print(np.ones(3))
print(np.ones((2,2)))

[1. 1. 1.]
[[1. 1.]
 [1. 1.]]


In [77]:
#array or matrix with any number
print(np.full(6,100))
print(np.full((2,3),5))

[100 100 100 100 100 100]
[[5 5 5]
 [5 5 5]]


In [79]:
#array or matrix with any number
print(np.full_like(A,100))
print(np.full_like(B,5))

[100 100 100]
[[5. 5. 5.]
 [5. 5. 5.]]


In [80]:
#Random decimal numbers
np.random.rand(3,2)

array([[0.34746261, 0.4432234 ],
       [0.07492893, 0.52342718],
       [0.4528971 , 0.27530981]])

In [83]:
#Random integer numbers
print(np.random.randint(7,size=(4,3)))
print(np.random.randint(3,7,size=(4,3)))
print(np.random.randint(-10,7,size=(4,3)))

[[5 3 2]
 [4 4 3]
 [3 5 6]
 [3 0 2]]
[[5 6 5]
 [6 6 4]
 [4 4 4]
 [4 3 5]]
[[ 2  6  3]
 [-9  5 -4]
 [-6 -9  0]
 [ 1 -7 -3]]


In [84]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [87]:
#repeat an array
arr = np.array([[1,2,3]])
q = np.repeat(arr,3)
p = np.repeat(arr,3, axis=0)
print(q)
print(p)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [134]:
#create array D
D = np.full((5,5),0)
D[0,:] = 1
D[:,0]=1
D[2,2] = 9
D[4,:] = 1
D[:,4]=1
print(D)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [136]:
#create array D
D = np.full((5,5),1)
print(D)

b= np.full((3,3),0)
b[1,1]=9
print(b)

D[1:4,1:4]=b
print(D)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### Be careful when copying arrays

In [137]:
#suppose we have two arrays X and Y
X = np.array([1,2,3])
#set X to Y
Y = X
#change an element of Y
Y[1] = 40

#print X
print(X)

[ 1 40  3]


In [139]:
#to avoid the case above, make a copy of X when assigning to Y
X = np.array([1,2,3])
#set X to Y
Y = X.copy()
#change an element of Y
Y[1] = 40

#print X
print(X)

#print Y
print(Y)

[1 2 3]
[ 1 40  3]


### NumPy Array Mathematics
[Click For More](https://numpy.org/doc/stable/reference/routines.math.html)

In [140]:
#create an array H
H = np.array([2,4,6,8,10])
print(H)

[ 2  4  6  8 10]


In [149]:
print(H - 2)
print(H + 2)
print(H / 2)
print(H * 2)
print(H**2)
print(H%2)

[0 2 4 6 8]
[ 4  6  8 10 12]
[1. 2. 3. 4. 5.]
[ 4  8 12 16 20]
[  4  16  36  64 100]
[0 0 0 0 0]


In [144]:
#create two arrays T1 and T2
T1 = np.array([1,2,3,4,5,6])
T2 = np.array([1,2,1,3,1,4])
print(T1)
print(T2)

[1 2 3 4 5 6]
[1 2 1 3 1 4]


In [150]:
print(T1+T2)
print(T1*T2)
print(T1/T2)
print(T1%T2)
print(T1**T2)
print(np.sin(T1))

[ 2  4  4  7  6 10]
[ 1  4  3 12  5 24]
[1.         1.         3.         1.33333333 5.         1.5       ]
[0 0 0 1 0 2]
[   1    4    3   64    5 1296]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


#### LInear Algebra
[Click For More](https://numpy.org/doc/stable/reference/routines.linalg.html?highlight=linear%20algebra)

In [151]:
#create two matrices M1 and M2
M1 = np.ones((2,3))
print(M1)

M2 = np.full((3,2),2)
print(M1)

#dot() and matmul() give the same result
print(np.matmul(M1,M2))
print(M1.dot(M2))

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6. 6.]
 [6. 6.]]
[[6. 6.]
 [6. 6.]]


In [159]:
#create a square matrix M3
M3 = np.array([[1,2,3],[3,5,6],[7,3,9]])

#find the determinant of M3
np.linalg.det(M3)

-20.99999999999999

In [160]:
#for more on linear Algebra click on the link above

#### Statistics
[Click For More](https://numpy.org/doc/stable/reference/routines.statistics.html?highlight=statistic)

In [162]:
print(np.min(M1))
print(np.max(M1))
print(np.sum(M1))

1.0
1.0
6.0


In [164]:
print(np.min(M1, axis=0))
print(np.max(M1, axis=0))
print(np.sum(M1, axis=0))
print(np.min(M1, axis=1))
print(np.max(M1, axis=1))
print(np.sum(M1, axis=1))

[1. 1. 1.]
[1. 1. 1.]
[2. 2. 2.]
[1. 1.]
[1. 1.]
[3. 3.]


In [165]:
#for more use the link above

#### Reorganizing Arrays
[Click For More on Reshape()](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy.reshape)

In [178]:
#change shape of M4 and save into M5
M4 = np.array([[1,2,3,4],[5,6,7,8]])
print(M4)
print(M4.shape)

M5 = M4.reshape((2,2,2))
print(M5)
print(M5.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [181]:
#change shape of M3 and save into M6
print(M3)
print(M3.shape)

M6 = M3.reshape((1,1,9))
print(M6)
print(M6.shape)

[[1 2 3]
 [3 5 6]
 [7 3 9]]
(3, 3)
[[[1 2 3 3 5 6 7 3 9]]]
(1, 1, 9)


In [182]:
#vertically stacking vectors
M7 = np.array([1,2,3,4])
M8 = np.array([5,6,7,8])

np.vstack([M8,M7,M7,M8])

array([[5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [183]:
#horizontal stacking 
M7 = np.array([1,2,3,4])
M8 = np.array([5,6,7,8])

np.hstack([M7,M8])

array([1, 2, 3, 4, 5, 6, 7, 8])